on: 
  push

name: testinstall

jobs:
  testinstall:
    runs-on: ${{ matrix.config.os }}
        
    name: ${{ matrix.config.os }}
        
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest, r: '4.1', bioc: 'devel'}
        - {os: windows-latest, r: '4.1', bioc: 'devel'}
        #- {os: ubuntu-latest, r: '4.1', bioc: 'devel'}
        
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Get GITHUB_WORKSPACE
        run: |
          Sys.getenv("GITHUB_WORKSPACE")
          Sys.getenv("PATH")
        shell: Rscript {0}

      - name: Install cygwin
        if: runner.os == 'Windows'
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake gcc-g++
            
      - name: Install Rhtslib
        run: |
          install.packages("BiocManager")
          BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE)
          BiocManager::install("Rhtslib")
        shell: Rscript {0}
        
        