on: 
  push

name: testinstall

jobs:
  testinstall:
    runs-on: ${{ matrix.config.os }}
        
    name: ${{ matrix.config.os }}
        
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest, r: '4.1', bioc: 'devel'}
        #- {os: windows-latest, r: '4.1', bioc: 'devel'}
        #- {os: ubuntu-latest, r: '4.1', bioc: 'devel'}
        
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Get GITHUB_WORKSPACE
        run: |
          Sys.getenv("GITHUB_WORKSPACE")
          Sys.getenv("PATH")
        shell: Rscript {0}

