on: 
  push

name: testinstall

jobs:
  testinstall:
    runs-on: ${{ matrix.config.os }}
        
    name: ${{ matrix.config.os }}
        
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-latest, r: 'devel', bioc: 'devel'}
        - {os: windows-latest, r: 'devel', bioc: 'devel'}
        #- {os: ubuntu-latest, r: 'devel', bioc: 'devel'}
        
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Get GITHUB_WORKSPACE
        run: |
          Sys.getenv("GITHUB_WORKSPACE")
          Sys.getenv("PATH")
        shell: Rscript {0}

            
      - name: Install Rhtslib
        run: |
          install.packages("BiocManager")
          BiocManager::install(version = "${{ matrix.config.bioc }}", ask = FALSE)
          #BiocManager::install("Rhtslib")
          BiocManager::install("zlibbioc")
          install.packages('Rhtslib', repos = 'https://bioconductor.r-universe.dev')
        shell: Rscript {0}
        
        