on:
  push

name: snakemake-test

jobs:
  snakemake-test:
    name: test snakemake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        include:
        - os: macos-latest
          rversion: '4.3'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Install R (macOS)
        uses: r-lib/actions/setup-r@v2
        if: runner.os == 'macOS'
        with:
          r-version: ${{ matrix.rversion }}
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: bioconda,conda-forge,defaults
          activate-environment: base

      - name: Install Snakemake (macOS)
        if: runner.os == 'macOS'
        run: |
          conda create -c conda-forge -c bioconda -n snakemake snakemake
          conda activate snakemake
          snakemake --help
      

        
