on:
  push

name: jpeg-test

jobs:
  jpeg-test:
    name: test-jpeg
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        include:
        - os: macos-latest
          rversion: 'devel'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.rversion }}
      
      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install jpeg
          echo 'export PATH="/opt/homebrew/opt/jpeg/bin:$PATH"' >> /Users/runner/.bash_profile
      
      - name: Get path to jpeg
        if: runner.os == 'macOS'
        run: |
          cat /Users/runner/.bash_profile
          find $(brew --prefix jpeg) -name jpeglib.h
      
      - name: Install jpeg
        env:
          LDFLAGS: "-L/opt/homebrew/opt/jpeg/lib"
          CPPFLAGS: "-I/opt/homebrew/opt/jpeg/include"
          PKG_CONFIG_PATH: "/opt/homebrew/opt/jpeg/lib/pkgconfig"
          CFLAGS: "-I/opt/homebrew/opt/jpeg/include"
        run: |
          install.packages("jpeg")
        shell: Rscript {0}
      

        
